main_branches: &main_branches
  filters:
    branches:
      only:
        - circleci
        - develop
        - master
    tags:
      ignore: /.*/

tags_only: &tags_only
    filters:
        tags:
            only: /.*/

version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/via-web-admin
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/via-web-admin
  bundle_dependencies:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/via-web-admin
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/via-web-admin
    steps:
      - checkout
      - restore_cache:
          # special step to restore the dependency cache
          keys: 
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}            
      - run:
          name: Build Project
          command: npm run build
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/via-web-admin/build
  test:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/via-web-admin
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running tests
          command: npm run test          
  deploy:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy Master to Heroku
            command: |
              git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git master

workflows:
  version: 2
  "Build and Test":
    jobs:
      - checkout_code:
          <<: *main_branches
      - bundle_dependencies:
          requires:
            - checkout_code
          <<: *main_branches
      - build:
          <<: *main_branches
          requires:
            - bundle_dependencies
      - test:
          <<: *main_branches
          requires:
            - bundle_dependencies

  'Build, Test, and Deploy':
        jobs:
            - checkout_code:
                  <<: *tags_only
            - bundle_dependencies:
                  requires:
                      - checkout_code
                  <<: *tags_only
            - build:
                  <<: *tags_only
                  requires:
                      - bundle_dependencies
            - test:
                  <<: *tags_only
                  requires:
                      - bundle_dependencies
            - hold:
                  <<: *tags_only
                  type: approval
                  requires:
                      - build
                      - test
            - deploy:
                  <<: *tags_only
                  requires:
                      - hold
